version: "3.3"

services:
    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        image: nginx
        depends_on:
            - wordpress
        volumes:
            - data_n:/var/www/html/
        restart: on-failure
        ports:
            - "443:443"
        networks:
            - docker_network

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        image: wordpress
        volumes:
            - data_n:/var/www/html/
        restart: on-failure
        env_file: .env
        networks:
            - docker_network
   
    mariadb:
        container_name: mariadb
        build: ./requirements/mariadb/
        image: mariadb
        volumes:
            - data_db:/var/lib/mysql/
        restart: on-failure
        env_file: .env
        networks:
            - docker_network

volumes:
    data_n: 
        driver: local
        driver_opts:
                type: 'none'
                o: 'bind'
                device: /home/user42/data/wordpress
    data_db:
        driver: local
        driver_opts:
                type: 'none'
                o: 'bind'
                device: /home/user42/data/mariadb

networks:
    docker_network:
